/*
========================================================
Code Overview
--------------------------------------------------------
Purpose:
- Read the connection string from appsettings.json
- Create AppDbContext manually in a console application
- Retrieve data from all main tables in TrainingCenterDB
- Print each Student table's data using function
- Show the SQL generated by EF Core before execution

Layout:
- Build configuration
- Read connection string
- Build DbContextOptions
- Create AppDbContext
- Test database connection
- Call retrieval method for Student table's data


========================================================
*/

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using TrainingCenter.Data;

// ========================================================
// Build configuration so the console app can read
// appsettings.json from the output folder
// ========================================================
IConfiguration configuration = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())              // Current output folder
    .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true) // Load appsettings.json
    .Build();

// ========================================================
// Read the connection string from appsettings.json
// ========================================================
string? connectionString = configuration.GetConnectionString("DefaultConnection");

// Validate that the connection string exists
if (string.IsNullOrWhiteSpace(connectionString))
{
    Console.WriteLine("Connection string 'DefaultConnection' was not found.");
    return;
}

// ========================================================
// Build DbContextOptions manually for AppDbContext
// ========================================================
var options = new DbContextOptionsBuilder<AppDbContext>()
    .UseSqlServer(connectionString) // Tell EF Core to use SQL Server
    .Options;

// ========================================================
// Create AppDbContext manually
// ========================================================
using var context = new AppDbContext(options);

// ========================================================
// Check whether the database connection works
// ========================================================
bool canConnect = context.Database.CanConnect();

if (!canConnect)
{
    Console.WriteLine("Could not connect to TrainingCenterDB.");
    return;
}

Console.WriteLine("Connected successfully to TrainingCenterDB.");
Console.WriteLine();



// ========================================================
// Call retrieval method
// ========================================================
RetrieveAndPrintStudents(context);


/// <summary>
/// Retrieves all students from the database, prints the generated SQL,
/// then prints the returned student data.
/// </summary>
/// <param name="context">The EF Core database context.</param>
static void RetrieveAndPrintStudents(AppDbContext context)
{
    // Build the query first (no execution yet)
    var query = context.Students
        .OrderBy(s => s.StudentId);

    // Show generated SQL before execution
    PrintGeneratedSql("Students", query.ToQueryString());

    // Execute query
    var students = query.ToList();

    // If no data exists, stop here
    if (students.Count == 0)
    {
        Console.WriteLine("No students found in the database.");
        Console.WriteLine();
        return;
    }

    Console.WriteLine("Students List:");
    Console.WriteLine("--------------");

    foreach (var student in students)
    {
        Console.WriteLine(
            $"Id: {student.StudentId}, " +
            $"Name: {student.FirstName} {student.LastName}, " +
            $"Email: {student.Email}, " +
            $"Status: {student.Status}, " +
            $"Phone: {student.PhoneNumber ?? "N/A"}");
    }

    Console.WriteLine();
    Console.WriteLine($"Total Students: {students.Count}");
    Console.WriteLine(new string('=', 70));
    Console.WriteLine();
}


static void PrintGeneratedSql(string tableName, string sqlQuery)
{
    Console.WriteLine($"Generated SQL Query for {tableName}:");
    Console.WriteLine(new string('-', 40));
    Console.WriteLine(sqlQuery);
    Console.WriteLine();
}
